# Configuração do site

# Importe o tema
theme: jekyll-theme-chirpy

# O idioma da página web › http://www.lingoes.net/en/translator/langcode.htm
# Se tiver o mesmo nome de um dos arquivos da pasta `_data/locales`, o idioma do layout também será alterado,
# caso contrário, a linguagem de layout usará o valor padrão 'en'.
lang: pt-BR

# Mude para o seu fuso horário› https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Recife

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Paulo Soares # O título principal

tagline: CyberSecurity | CTF Player | Bug Bounty | Pentest | Ethical Hacking | Red Team | Bug Hunter | SysAdmin | Linux | Windows # Ele será exibido como legenda

description: >- # Usado pelo seo meta e pelo feed atom
  Um tema Jekyll mínimo, responsivo e rico em recursos para redação técnica.

# Preencha o protocolo e o nome do host do seu site.
# Por exemplo 'https://username.github.io', observe que não termina com '/'.
url: "https://soarespaullo.github.io"

github:
  username: soarespaullo # Mude para seu nome de usuário do GitHub

twitter:
  username: twitter_username # Mude para seu nome de usuário do Twitter

  author:
  name: Paulo Soares
  url: https://github.com/soarespaullo/

social:
  # Mude para seu nome completo.
  # Ele será exibido como autor padrão das postagens e proprietário dos direitos autorais no rodapé
  name: Paulo Soares
  email: soarespaullo@proton.me # Mude para seu endereço de e-mail
  links:
    # O primeiro elemento serve como link do proprietário dos direitos autorais
    # - https://twitter.com/username # Mude para sua página inicial do Twitter
    # - https://github.com/username # Mude para sua página inicial do GitHub
    - https://www.linkedin.com/in/soarespaullo

# Configurações de verificação de site
webmaster_verifications:
  google: # Preencha seu código de verificação do Google
  bing: # Preencha seu código de verificação do Bing
  alexa: # Preencha seu código de verificação Alexa
  yandex: # Preencha seu código de verificação Yandex
  baidu: # Preencha seu código de verificação do Baidu
  facebook: # Preencha seu código de verificação do Facebook
  
# ↑ --------------------------
# O fim das configurações de `jekyll-seo-tag`

# Configurações de análise da web
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# Avatar na barra lateral, oferece suporte a recursos locais ou CORS
avatar: /assets/img/avatar/profile.jpg

# O URL da imagem de visualização social de todo o site usada na meta tag SEO `og:image`.
# Ele pode ser substituído por um `page.image` personalizado no início.
social_preview_image: # Recursos de string, locais ou CORS

# Tipo booleano, a opção global para TOC nas postagens
toc: true

comments:
  # Mudança global para o sistema pós-comentário. Mantê-lo vazio significa desabilitado.
  provider: # [disqus | utterances | giscus]
  # As opções do provedor são as seguintes:
  disqus:
    shortname: soarespaullo # Preencha com o nome abreviado do Disqus. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # Configurações de declarações › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Ativos estáticos auto-hospedados, opcionais › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # A opção de recurso PWA (instalável)
  cache:
    enabled: true # A opção de cache offline PWA
    # Os caminhos definidos aqui serão excluídos do cache do PWA.
    # Geralmente seu valor é o `baseurl` de outro site que
    # compartilha o mesmo nome de domínio do site atual.
    deny_paths:
      # - "/example" # URLs correspondentes a `<SITE_URL>/example/*` não serão armazenados em cache pelo PWA

paginate: 10

# URL base do seu site
baseurl: "/blog"

# ------------ As seguintes opções não são recomendadas para serem modificadas ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Opções Rouge › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Habilite comentários nas postagens.
      toc: true # Exibir coluna TOC nas postagens.
      # NÃO modifique o seguinte parâmetro a menos que você esteja confiante o suficiente
      # para atualizar o código de todos os outros links de postagem neste projeto.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
